# Generated by Django 6.0.4 on 2026-04-21 20:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id_produkt', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('cenaBrutto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategoria', models.CharField(max_length=100)),
                ('kolor', models.CharField(max_length=50)),
                ('rozmiar', models.CharField(blank=True, max_length=20)),
                ('zdjecie', models.CharField(blank=True, max_length=255)),
                ('stanMagazynowy', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'produkt',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('imie', models.CharField(blank=True, max_length=50)),
                ('nazwisko', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dataRejestracji', models.DateTimeField(auto_now_add=True)),
                ('statusUzytkownika', models.CharField(choices=[('aktywny', 'Aktywny'), ('zablokowany', 'Zablokowany')], default='aktywny', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'uzytkownik',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id_administrator', models.AutoField(primary_key=True, serialize=False)),
                ('id_uzytkownik', models.OneToOneField(db_column='id_uzytkownik', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id_koszyk', models.AutoField(primary_key=True, serialize=False)),
                ('dataUtworzenia', models.DateTimeField(auto_now_add=True)),
                ('rezerwacjaDo', models.DateTimeField(blank=True, null=True)),
                ('id_uzytkownik', models.OneToOneField(db_column='id_uzytkownik', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'koszyk',
            },
        ),
        migrations.CreateModel(
            name='PozycjaKoszyka',
            fields=[
                ('id_pozycjakoszyka', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc', models.IntegerField(default=1)),
                ('cenaJednostkowa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_koszyk', models.ForeignKey(db_column='id_koszyk', on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='api.koszyk')),
                ('id_produkt', models.ForeignKey(db_column='id_produkt', on_delete=django.db.models.deletion.CASCADE, to='api.produkt')),
            ],
            options={
                'db_table': 'pozycjakoszyka',
            },
        ),
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('id_opinia', models.AutoField(primary_key=True, serialize=False)),
                ('ocena', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('komentarz', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('id_uzytkownik', models.ForeignKey(db_column='id_uzytkownik', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_produkt', models.ForeignKey(db_column='id_produkt', on_delete=django.db.models.deletion.CASCADE, related_name='opinie', to='api.produkt')),
            ],
            options={
                'db_table': 'opinia',
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id_zamowienie', models.AutoField(primary_key=True, serialize=False)),
                ('dataZlozenia', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('oczekujące', 'Oczekujące'), ('w realizacji', 'W realizacji'), ('wysłane', 'Wysłane'), ('zakończone', 'Zakończone'), ('anulowane', 'Anulowane')], default='oczekujące', max_length=20)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_uzytkownik', models.ForeignKey(db_column='id_uzytkownik', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zamowienie',
            },
        ),
        migrations.CreateModel(
            name='PozycjaZamowienia',
            fields=[
                ('id_pozycjazamowienia', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc', models.IntegerField(default=1)),
                ('cenaJednostkowa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_produkt', models.ForeignKey(db_column='id_produkt', on_delete=django.db.models.deletion.CASCADE, to='api.produkt')),
                ('id_zamowienie', models.ForeignKey(db_column='id_zamowienie', on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='api.zamowienie')),
            ],
            options={
                'db_table': 'pozycjazamowienia',
            },
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('id_platnosc', models.AutoField(primary_key=True, serialize=False)),
                ('metoda', models.CharField(choices=[('karta', 'Karta'), ('przelew', 'Przelew'), ('blik', 'BLIK'), ('paypal', 'PayPal')], max_length=20)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('oczekująca', 'Oczekująca'), ('zakończona', 'Zakończona'), ('odrzucona', 'Odrzucona')], default='oczekująca', max_length=20)),
                ('znacznikCzasu', models.DateTimeField(auto_now_add=True)),
                ('id_uzytkownik', models.ForeignKey(db_column='id_uzytkownik', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_zamowienie', models.ForeignKey(db_column='id_zamowienie', on_delete=django.db.models.deletion.CASCADE, related_name='platnosci', to='api.zamowienie')),
            ],
            options={
                'db_table': 'platnosc',
            },
        ),
        migrations.CreateModel(
            name='AdresDostawy',
            fields=[
                ('id_adres_dostawy', models.AutoField(primary_key=True, serialize=False)),
                ('ulica', models.CharField(max_length=100)),
                ('miasto', models.CharField(max_length=50)),
                ('kodPocztowy', models.CharField(max_length=10)),
                ('kraj', models.CharField(default='Polska', max_length=50)),
                ('id_zamowienie', models.OneToOneField(db_column='id_zamowienie', on_delete=django.db.models.deletion.CASCADE, related_name='adres_dostawy', to='api.zamowienie')),
            ],
            options={
                'db_table': 'adresdostawy',
            },
        ),
        migrations.CreateModel(
            name='Zwrot',
            fields=[
                ('id_zwrot', models.AutoField(primary_key=True, serialize=False)),
                ('powod', models.TextField()),
                ('status', models.CharField(choices=[('oczekujący', 'Oczekujący'), ('przyjęty', 'Przyjęty'), ('odrzucony', 'Odrzucony')], default='oczekujący', max_length=20)),
                ('dataZgloszenia', models.DateTimeField(auto_now_add=True)),
                ('dataAktualizacji', models.DateTimeField(blank=True, null=True)),
                ('id_zamowienie', models.ForeignKey(db_column='id_zamowienie', on_delete=django.db.models.deletion.CASCADE, related_name='zwroty', to='api.zamowienie')),
            ],
            options={
                'db_table': 'zwrot',
            },
        ),
    ]
