# Generated by Django 6.0.4 on 2026-04-22 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_produkt_zdjecie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='rozmiar',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='stanMagazynowy',
        ),
        migrations.CreateModel(
            name='RozmiarProduktu',
            fields=[
                ('id_rozmiar', models.AutoField(primary_key=True, serialize=False)),
                ('rozmiar', models.CharField(max_length=10)),
                ('stanMagazynowy', models.IntegerField(default=0)),
                ('id_produkt', models.ForeignKey(db_column='id_produkt', on_delete=django.db.models.deletion.CASCADE, related_name='rozmiary', to='api.produkt')),
            ],
            options={
                'db_table': 'rozmiar_produktu',
                'unique_together': {('id_produkt', 'rozmiar')},
            },
        ),
    ]
