# Generated by Django 6.0.4 on 2026-04-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_produkt_rozmiar_remove_produkt_stanmagazynowy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycjakoszyka',
            name='rozmiar',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
