# Generated by Django 5.0.4 on 2026-05-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycjazamowienia',
            name='rozmiar',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
